const LOADING = "LOADING";
const ENTER_SUCCESS = "ENTER_SUCCESS";
const ENTER_ERROR = "ENTER_ERROR";

const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";

const GET_PLAYERS_SUCCESS = "GET_PLAYERS_SUCCESS";

const GET_MANAGER_SUCCESS = "GET_MANAGER_SUCCESS";

const GET_WINNER_SUCCESS = "GET_WINNER_SUCCESS";
const GET_WINNER_ERROR = "GET_WINNER_ERROR";

export {
  LOADING,
  ENTER_SUCCESS,
  ENTER_ERROR,
  GET_BALANCE_SUCCESS,
  GET_PLAYERS_SUCCESS,
  GET_MANAGER_SUCCESS,
  GET_WINNER_SUCCESS,
  GET_WINNER_ERROR
};
